[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install --no-cache-dir --disable-pip-version-check -r simple_requirements.txt"
]

[start]
cmd = "gunicorn simple_app:app --bind 0.0.0.0:$PORT --timeout 300 --workers 1 --log-level info" 
