#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Amazon Associates theme definitions for the Jobcan + PDF lightweight site."""

from typing import Dict, List, Tuple

# Approved theme pool. Display copy and Amazon search queries are intentionally
# separated so card titles never leak into the destination query string.
AMAZON_THEME_POOL: List[Dict[str, object]] = [
    {
        "id": "consulting-problem-solving",
        "enabled": True,
        "category_label": "思考法",
        "title": "コンサルの思考法・問題解決",
        "query": "ロジカルシンキング 本",
        "query_variants": ["仮説思考", "問題解決 本", "戦略思考 本", "ケース面接 本"],
        "cta": "思考法の本を見る",
        "priority_page_types": ["landing", "info", "generic"],
        "priority_path_prefixes": ["/", "/recommend", "/faq"],
    },
    {
        "id": "slide-presentation",
        "enabled": True,
        "category_label": "資料作成",
        "title": "資料作成・プレゼン",
        "query": "PowerPoint 資料作成 本",
        "query_variants": ["プレゼン 本", "図解 本", "ビジネスライティング 本"],
        "cta": "資料作成の本を見る",
        "priority_page_types": ["landing", "tool_index", "info"],
        "priority_path_prefixes": ["/", "/tools", "/recommend"],
    },
    {
        "id": "pdf-document-work",
        "enabled": True,
        "category_label": "PDF・書類",
        "title": "PDF・書類作業を楽にする",
        "query": "ドキュメントスキャナー",
        "query_variants": ["PDF 編集", "書類整理 グッズ", "USB-Cハブ"],
        "cta": "PDF作業向けを見る",
        "priority_page_types": ["tool", "tool_index", "landing"],
        "priority_path_prefixes": ["/tools/pdf", "/tools", "/recommend"],
    },
    {
        "id": "focus-productivity",
        "enabled": True,
        "category_label": "集中環境",
        "title": "集中・生産性を高める",
        "query": "タイマー 勉強",
        "query_variants": ["ノイズキャンセリング", "モニター 仕事", "キーボード マウス セット"],
        "cta": "作業環境を見る",
        "priority_page_types": ["landing", "tool", "trust_sensitive", "info"],
        "priority_path_prefixes": ["/", "/autofill", "/recommend"],
    },
    {
        "id": "business-books",
        "enabled": True,
        "category_label": "ビジネス書",
        "title": "ビジネス書を探す",
        "query": "ビジネス書 おすすめ",
        "query_variants": ["仕事術 本", "生成AI 本", "コンサル 本"],
        "cta": "ビジネス書を見る",
        "priority_page_types": ["landing", "info", "generic"],
        "priority_path_prefixes": ["/", "/faq", "/recommend"],
    },
]

AMAZON_PURPOSE_GENRES = AMAZON_THEME_POOL

PATH_KEYWORD_RULES: List[Tuple[str, List[str]]] = [
    ("/tools/pdf", ["PDF 編集", "ドキュメントスキャナー", "書類整理 グッズ"]),
    ("/tools", ["PDF 編集", "ロジカルシンキング 本", "PowerPoint 資料作成 本"]),
    ("/autofill", ["テンキー", "タイマー 勉強", "ロジカルシンキング 本"]),
    ("/faq", ["ビジネス書 おすすめ", "仕事効率化 グッズ", "PDF 編集"]),
    ("/recommend", ["ロジカルシンキング 本", "PowerPoint 資料作成 本", "ドキュメントスキャナー"]),
    ("/", ["ロジカルシンキング 本", "PowerPoint 資料作成 本", "PDF 編集"]),
]

PAGE_TYPE_KEYWORDS: Dict[str, List[str]] = {
    "landing": ["ロジカルシンキング 本", "PowerPoint 資料作成 本", "PDF 編集"],
    "tool": ["PDF 編集", "ドキュメントスキャナー", "仕事効率化 グッズ"],
    "tool_index": ["PDF 編集", "ロジカルシンキング 本", "PowerPoint 資料作成 本"],
    "trust_sensitive": ["タイマー 勉強", "ノイズキャンセリング", "ビジネス書 おすすめ"],
    "info": ["ビジネス書 おすすめ", "仕事術 本", "PDF 編集"],
    "legal": ["ビジネス書 おすすめ", "仕事効率化 グッズ"],
    "contact": ["タイマー 勉強", "デスクワーク 便利グッズ"],
    "generic": ["ロジカルシンキング 本", "ビジネス書 おすすめ", "PDF 編集"],
}

LIGHTWEIGHT_AMAZON_SECTIONS: Dict[str, Dict[str, object]] = {
    "home": {
        "anchor_id": "amazon-consulting-items",
        "title": "コンサルワークを整えるアイテム",
        "lead": "勤怠入力やPDF整理の合間に、思考整理・資料作成・作業環境を整えたい方向けの導線です。",
        "more_label": "コンサル向けアイテムをまとめて見る",
        "more_path": "/recommend",
        "items": [
            {
                "category_label": "思考法",
                "title": "コンサルの思考法・問題解決",
                "description": "仮説思考やロジカルシンキングを学び直したい方向けです。",
                "query": "ロジカルシンキング 本",
                "query_variants": ["仮説思考", "問題解決 本", "戦略思考 本"],
                "cta": "思考法の本を見る",
            },
            {
                "category_label": "資料作成",
                "title": "資料作成・プレゼン",
                "description": "提案書や報告資料を見やすく整えたい方向けです。",
                "query": "PowerPoint 資料作成 本",
                "query_variants": ["プレゼン 本", "図解 本", "ビジネスライティング 本"],
                "cta": "資料作成の本を見る",
            },
            {
                "category_label": "PDF・書類",
                "title": "PDF・書類作業を楽にする",
                "description": "PDF整理や書類確認が多い方の周辺アイテムを探せます。",
                "query": "ドキュメントスキャナー",
                "query_variants": ["PDF 編集", "書類整理 グッズ", "USB-Cハブ"],
                "cta": "PDF作業向けを見る",
            },
        ],
    },
    "autofill": {
        "anchor_id": "amazon-autofill-items",
        "title": "勤怠入力まわりを整えるアイテム",
        "lead": "Jobcan入力や確認作業を少し楽にしたい方向けの、控えめな補助導線です。",
        "more_label": "関連アイテムをまとめて見る",
        "more_path": "/recommend",
        "items": [
            {
                "category_label": "入力補助",
                "title": "数字入力をしやすくする",
                "description": "テンキーやキーボードなど、入力作業の手元を整えたい方向けです。",
                "query": "テンキー",
                "query_variants": ["ワイヤレス テンキー", "キーボード マウス セット"],
                "cta": "入力補助を見る",
            },
            {
                "category_label": "時間管理",
                "title": "作業時間を区切って集中する",
                "description": "締め作業や確認作業を短時間で進めたいときに役立つ候補です。",
                "query": "タイマー 勉強",
                "query_variants": ["デスク タイマー", "ポモドーロ タイマー"],
                "cta": "時間管理を見る",
            },
            {
                "category_label": "集中環境",
                "title": "集中できる作業環境を整える",
                "description": "入力前後の確認作業を落ち着いて進めたい方向けです。",
                "query": "ノイズキャンセリング",
                "query_variants": ["デスクワーク 便利グッズ", "モニター 仕事"],
                "cta": "作業環境を見る",
            },
        ],
    },
    "tools": {
        "anchor_id": "amazon-tools-items",
        "title": "Jobcan・PDF作業にあわせて見るアイテム",
        "lead": "ツール利用を主役にしながら、PDF整理や資料作成を補助するアイテムを控えめに紹介します。",
        "more_label": "カテゴリ別にまとめて見る",
        "more_path": "/recommend",
        "items": [
            {
                "category_label": "PDF",
                "title": "PDFや書類作業が多い方向け",
                "description": "PDF編集、書類整理、スキャンまわりの候補を確認できます。",
                "query": "PDF 編集",
                "query_variants": ["ドキュメントスキャナー", "書類整理 グッズ"],
                "cta": "PDF作業向けを見る",
            },
            {
                "category_label": "資料作成",
                "title": "資料作成を効率化したい方向け",
                "description": "プレゼンや図解、ビジネスライティングの本を探せます。",
                "query": "PowerPoint 資料作成 本",
                "query_variants": ["プレゼン 本", "図解 本"],
                "cta": "資料作成の本を見る",
            },
            {
                "category_label": "思考整理",
                "title": "問題解決の型を学び直す",
                "description": "コンサルワークの思考整理に使いやすい本を探せます。",
                "query": "ロジカルシンキング 本",
                "query_variants": ["仮説思考", "問題解決 本"],
                "cta": "思考法の本を見る",
            },
        ],
    },
    "pdf": {
        "anchor_id": "amazon-pdf-items",
        "title": "PDF・書類作業を楽にするアイテム",
        "lead": "提案書や請求書など、PDF資料を扱うことが多い方向けの補助導線です。",
        "more_label": "PDF作業向けアイテムをまとめて見る",
        "more_path": "/recommend",
        "items": [
            {
                "category_label": "書類整理",
                "title": "紙資料をPDF化しやすくする",
                "description": "ドキュメントスキャナーなど、紙とPDFの行き来が多い方向けです。",
                "query": "ドキュメントスキャナー",
                "query_variants": ["書類 スキャン", "書類整理 グッズ"],
                "cta": "書類整理を見る",
            },
            {
                "category_label": "接続まわり",
                "title": "PDF確認環境を整える",
                "description": "外部モニターやUSB-Cハブなど、資料確認の環境を整えたい方向けです。",
                "query": "USB-Cハブ",
                "query_variants": ["モニター 仕事", "ノートPCスタンド"],
                "cta": "確認環境を見る",
            },
            {
                "category_label": "資料作成",
                "title": "読みやすい資料を作る",
                "description": "図解やプレゼンの型を学びたい方向けの本を探せます。",
                "query": "図解 本",
                "query_variants": ["プレゼン 本", "PowerPoint 資料作成 本"],
                "cta": "資料作成の本を見る",
            },
        ],
    },
    "faq": {
        "anchor_id": "amazon-faq-items",
        "title": "作業環境を整えたい方へ",
        "lead": "FAQを確認したあとに、入力・PDF・集中環境の周辺アイテムも見比べられます。",
        "more_label": "カテゴリ別のおすすめを見る",
        "more_path": "/recommend",
        "items": [
            {
                "category_label": "入力補助",
                "title": "入力しやすい環境を整える",
                "description": "テンキーやマウス、キーボードなどをまとめて確認できます。",
                "query": "テンキー",
                "query_variants": ["ワイヤレスマウス", "キーボード マウス セット"],
                "cta": "入力補助を見る",
            },
            {
                "category_label": "PDF・書類",
                "title": "PDFや書類作業を整える",
                "description": "PDF編集や書類整理が多い方向けの候補を探せます。",
                "query": "PDF 編集",
                "query_variants": ["ドキュメントスキャナー", "書類整理 グッズ"],
                "cta": "PDF作業向けを見る",
            },
            {
                "category_label": "ビジネス書",
                "title": "仕事の進め方を見直す",
                "description": "思考法や仕事術の本を探したい方向けです。",
                "query": "ビジネス書 おすすめ",
                "query_variants": ["仕事術 本", "ロジカルシンキング 本"],
                "cta": "ビジネス書を見る",
            },
        ],
    },
    "recommend": {
        "anchor_id": "recommend-categories",
        "title": "コンサルワーク向けアイテムおすすめ",
        "lead": "Jobcan入力、PDF・書類作業、資料作成、集中環境を整えたい方向けにカテゴリ別でまとめています。",
        "max_items": 4,
        "items": [
            {
                "category_label": "思考法",
                "title": "コンサルの思考法・問題解決",
                "description": "仮説思考、問題解決、戦略思考などを学び直したい方向けです。",
                "query": "ロジカルシンキング 本",
                "query_variants": ["仮説思考", "問題解決 本", "戦略思考 本"],
                "cta": "思考法の本を見る",
            },
            {
                "category_label": "資料作成",
                "title": "資料作成・プレゼン",
                "description": "提案書、報告書、図解、プレゼンの型を整えたい方向けです。",
                "query": "PowerPoint 資料作成 本",
                "query_variants": ["プレゼン 本", "図解 本", "ビジネスライティング 本"],
                "cta": "資料作成の本を見る",
            },
            {
                "category_label": "PDF・書類",
                "title": "PDF・書類作業を楽にする",
                "description": "PDF資料、スキャン書類、提出前確認が多い方向けです。",
                "query": "ドキュメントスキャナー",
                "query_variants": ["PDF 編集", "書類整理 グッズ", "USB-Cハブ"],
                "cta": "PDF作業向けを見る",
            },
            {
                "category_label": "集中環境",
                "title": "集中・生産性を高める",
                "description": "短時間で確認・入力・資料作成を進めたい方向けです。",
                "query": "タイマー 勉強",
                "query_variants": ["ノイズキャンセリング", "モニター 仕事", "キーボード マウス セット"],
                "cta": "作業環境を見る",
            },
            {
                "category_label": "ビジネス書",
                "title": "ビジネス書を探す",
                "description": "仕事術、生成AI活用、コンサルワークの本を探したい方向けです。",
                "query": "ビジネス書 おすすめ",
                "query_variants": ["生成AI 本", "仕事術 本", "コンサル 本"],
                "cta": "ビジネス書を見る",
            },
        ],
    },
}
